language: java
mvn: test
notifications:
  email: nkweteyimdaisy@gmail.com
  slack:
    secure: xMopPo9ZKLqsUJbl/E/iiQz7/MI3M9dNJc94gXckEpQT+9Tj1JziaWs29RLzXygKhpZbqgStlYKsRTNyUaBOgjgSxKju/fqATZ03H3px2wz1smO7ioivAF0u35IycMNK7uZgt5oVNksGLXf+J1mTezm15c3uygTOmfUfhGoFL6xjPKTDpuGe4e6E5a1TnfvwUUmMoNY/25RBSOa6Qc76Np+GhROll2vkX1wLiK9KzGVEcXS7epIEHM3dC27m8o+dLFQ8z9okqrMb+ctC7prfaO+u/D3xdO5D/QfON+iVXsNx4cqP80JWSmS4J0RQmFHWcI3e1iYsx99vAsbgRPxq//IvTm3flnvNPFxNy2JdzbXQalGox43q3bLMmRhu1D6AB1EmPmVKmT1eG+Q5Qbh1uEOWGVGGybP/VJmcBT4e3slAom9/vapDFYJ7Owq59zRLZg5gQ6bvY48NHbjji1uFLcfbLs3Zoc/L6SUXm5lFZVUVM2SeQaYcKhE/Pha6vymCuG4s83gpWOAfiK+C7jSI23aTfOmCV7ehrEoYAVN19hqjgiE5EDXXmNaIkCn5S+FflwkB4INNkY1fjdmMTLt6rIWQAd8jkFdaNAfJtMzn7vxV/g4QSNC9ChhVEaf3JashHelPoKjxqczciqoFP8Tvp+MGIISxLAVgBsNInAdvdPQ=
